### ISSUE TITLE
Rename default branches from 'master' to 'main'

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/comcifs.github.io#11]
Not sure if this is the best place to raise this issue, but it seems at least somewhat suitable since it applies to multiple IUCr GitHub repositories.

Recently, there has been a lot of debate about the potentially offensive nature of the "master" branch name [1,2]. This might be a polarising issue, but multiple entities in the Git ecosystem have started using different default branch names ("main" in the case of new GitHub repositories).

I think it may be worthwhile to think about applying similar changes to IUCr repositories (e.g. cif_core, TopoCif, etc.)  given that:
1. IUCr is an international organisation.
2. Some of the IUCr repositories already use "main" as the default branch (e.g. https://github.com/COMCIFS/instrument-geometry-info).
3. ITC volume G is still in preparation (it seems to contain at least a few references to IUCr repositories on GitHub). 

Some advice on renaming default GitHub branches is provided by GitHub itself [3].

[1] https://sfconservancy.org/news/2020/jun/23/gitbranchname/
[2] https://www.bbc.com/news/technology-53050955
[3] https://github.com/github/renaming

**Comment by jamesrhester** [comment]
I agree that shifting to `main` would be desirable, especially at this stage when most of the repositories are hardly used.  This issue should be raised for each active repository (there are only about 4?), so the contributors can object to the change if they wish. For the rest, we can silently change to `main` without causing undue trouble. 

Going forward, any new Github repositories will have a default branch of `main`.

**Comment by vaitkus** [comment]
The default branch of this repository should also be renamed to 'main', especially since this repository is likely to be referenced in published texts.

**Comment by jamesrhester** [comment]
Let's do that as soon as #23 is resolved.

**Comment by vaitkus** [comment]
Ok, #23 is now merged. The default branch can only be renamed by someone with admin privileges, so I leave this to @jamesrhester.

**Comment by jamesrhester** [comment]
Done
