### ISSUE TITLE
Formatting of values in Ranges

### ISSUE THREAD

**Issue by rowlesmr** [COMCIFS/comcifs.github.io#19]
There are different ways of formatting values in ranges:

```
    _type.contents                Real
    _enumeration.range            0.0:1.0
```
```
    _type.contents                Real
    _enumeration.range            0.:180.
```
```
    _type.contents                Real
    _enumeration.range            0:1.0
```
```
    _type.contents                Real
    _enumeration.range            0:90
```
```
    _type.contents                Integer
    _enumeration.range            1:48
```
```
    _type.contents                Real
    _enumeration.range            0.0:100.
```

IIRC, CIF2 specification separated the formatting of a value from it's interpretation as an integer/real, so this is purely cosmetic, but...

For consistency, should there be a standard way of doing things?

Reals -> 1.0
Integers -> 1

??

**Comment by jamesrhester** [comment]
This is really more appropriate for the [style guide](https://github.com/COMCIFS/comcifs.github.io/blob/master/accepted/ddlm_dictionary_style_guide.md) so I've transferred the issue.

**Comment by jamesrhester** [comment]
I agree that writing reals with at least one digit after the decimal point is more harmonious. In terms of the style guide, the stipulation would be that there should be at least one digit after the decimal point, and any following digits must be non-zero if present.
