### ISSUE TITLE
Principles for describing multi-block datasets

### ISSUE THREAD

**Issue by jamesrhester** [COMCIFS/comcifs.github.io#9]
This issue is a continuation of the [discussion originally started in the IUCr DDLm group](https://www.iucr.org/__data/iucr/lists/ddlm-group/msg01707.html). The proposal below is a copy of my most recent proposal to that group (edited for clarity 18-01-22)

### Definitions

- **Data blocks**: A _data block_ is a collection of _data values_ , each of which is associated with a _data name_ defined in a CIF dictionary such that these _data items_ may be arranged into tables ("loops") as described by the CIF dictionary.
- **Data sets**: A _data set_ is a collection of _data blocks_
- **Conformance**: An aggregate _conforms_ to a relational schema (like those described by CIF dictionaries) if the data contained can, in principle, be assigned unambiguously and consistently to cells in that relational schema
- **Appearance**: A category _appears_ in a data block if any data name belonging to it is either present, or is referred to via `_name.linked_item_id` of a data name that is present
- **Dictionary compatibility**: Two dictionaries describing data blocks are _compatible_ if, for all categories that appear in those data blocks, the dictionaries prescribe the same set of key data names
- **Data block compatibility**: Data blocks are _compatible_ if either (1) their dictionaries are compatible or (2) a unique value can be determined or assigned for any key data names that are absent from one of the incompatible dictionaries
- **Set categories**: A _Set_ category is a table for which only one row may be presented in a data block

### Rules
1. Multiple _data blocks_ are aggregated into a _data set_ by being presented in the same data container (e.g. file, zip archive,directory).
2. (Moved to definitions)
3. Dictionary conformance of individual data blocks is specified either by `audit_conform` data names in each block, or as-yet-undefined dataset-level `audit_dataset` datanames in any block. Dataset-level dictionaries override block-level dictionaries.
4. (Moved to definitions)
5. If a data name appearing in a data block is not defined in the dictionary to which that data block conforms, it is considered absent for the purposes of these principles
6. (Moved to definitions)
7. (Moved to definitions)
8. (Moved to definitions)
9. The set of "Set" categories for a data block is determined by the dictionary to which that data block conforms
10. A "Set" category may only be aggregated from multiple data blocks if at least one key data name for the "Set" category has been provided in the dictionary to which those data blocks conform.
11. Where a "Set" category has been provided with a key data name in the dictionary as per (10), and that key data name is not itself a child data name of some other data name, all child data names must also be provided in the dictionary.
12. The value of "Set" category key data names for a given data block may be assigned arbitrarily if missing
13. Values for child data names of "Set" category key data names may always be elided.

The guiding principle in designing these rules is "can we uniquely assign the values in a given data block into cells of the relational structure describing the whole dataset?". Reasons for failure that I can see might include:
1. Not being able to determine a single relational schema for the
dataset (contradictory dictionaries)
2. Not knowing the values of all the key data names in a row
3. Contradictory attribute values for the same key data name values

The conditions I've described above attempt to exclude these failure modes while also allowing maximum leeway in unambiguous situations (e.g. a category has only one value for a single key data name for the whole dataset, so the value is clear even for data blocks that don't explicitly allow for it in their dictionary).

**Comment by jamesrhester** [comment]
One inconvenience with the above proposal is that any looping of a `Set` category within a single data block (e.g. a summary block for a powder diffraction experiment listing all of the phases, i.e. `_pd_phase.id` appears in a loop) requires that data block to have a separate dictionary which essentially just changes the `_definition.class` of the category from `Set` to `Loop`. This is very cumbersome.
So as an immediate improvement, I propose the following interaction between `_audit.schema` and `Set` categories:
1. If `_audit.schema` is `Base`, `Set` categories behave as described in the proposal
2. If `_audit.schema` is not `Base`, all categories are `Loop` categories, i.e. are potentially looped in a single data block.

**Comment by jamesrhester** [comment]
As an extended example of how this would work, the current categories relating to experimental data in core CIF would be expanded to encompass multiple diffraction data sets and samples _for a single compound_ as follows:

1. `_diffrn.id` added to `Set` category `DIFFRN` (identifier for a diffraction dataset)
2. Child data names of `_diffrn.id` added to all `CELL_*` category keys
3. Child data names of `_diffrn.id` added to all `_diffrn_*` category keys
4. `_exptl_crystal.id` explicitly becomes the key of `EXPTL_CRYSTAL`
5. Child data names of `_exptl_crystal.id` are added to `EXPTL` and `EXPTL_CRYSTAL_*` category keys
6. `_diffrn.crystal_id` added to identify the crystal associated with this dataset (not part of key)

Note that the above (except (2) ) is essentially repeating what mmCIF already does, and in some cases (6) returning items that were removed from core CIF recently.

So, following the above principles, a dataset consisting of multiple diffraction measurements collected from 3 samples at room temperature and low temperature would be presented as a series of data blocks:

- 3 data blocks listing the crystal information (EXPTL_(CRYSTAL)) and stating `_exptl_crystal.id` somewhere in each block
- 2 data blocks giving the data sets and including a value of `_diffrn.id` somewhere in each block
- another data block giving information that does not depend on dataset or crystal

All data blocks would have `_audit_conform.*` data names referring to the thus-expanded core dictionary

Checking the principles:
(3) Is satisfied by the `_audit_conform.*` requirement
(9) is satisfied as `DIFFRN` and EXPTL(_CRYSTAL) have only one row per data block
(10) allows these data blocks to be aggregated as key data names have been provided for the Set categories
(11) we have provided the child data names in the dictionary
(12) not relevant
(13) eliding is allowed

**Comment by jamesrhester** [comment]
The only possible problem with the above scheme is where individual data names in Set categories have values that depend on both the particular dataset and the crystal. As a particular data set is always from a particular crystal, this problem might only arise for `EXPTL` items being particular to a given measurement.

If these situations do arise, I would advocate splitting Set categories to maintain purity - the names will no longer match the `_category.object` form due to the need to rename their category, but there will be no effect on data files.

**Comment by jamesrhester** [comment]
I've added a draft document on [using imgCIF with core CIF](/COMCIFS/comcifs.github.io/blob/master/draft/imgcif-with-core-guidelines.md) showing how these principles might be applied in practice. The key use of the current principles here is to manage categories in imgCIF that are potentially looped when those same categories in core CIF are not, in particular `diffrn_detector` and `diffrn_measurement`. It would be greatly appreciated if others could review both these and the above principles, particularly @jcbollinger and @vaitkus .

A DDLm version of the imgCIF dictionary would preserve the `Set` categories but include `_category_key.name`s, fulfilling the requirement (10) above.

**Comment by vaitkus** [comment]
I am a bit late with my reply, hopefully it is still somewhat relevant. Personally, I found the previous approach of importing the core dictionary and redefining relevant categories as looped slightly more robust since it reused the same import mechanisms as other dictionaries and thus allowed to reuse the existing validation software. However, I assume that this approach has been thoroughly discussed before moving away from it, so there is not much point in bringing it up again.

The new approach seems clear, however, I do have a few question/suggestions:
1. Rule 1 in the `Details` section states that all data blocks should contain the "`_audit_conform.dict_name        CORE_DIC`" line. However, given that the `_audit_conform.dict_name` is looped, wouldn't it be better to also include the `imgCIF` dictionary. Alternatively, since `imgCIF` dictionary (probably) imports the `CORE_CIF` dictionary, wouldn't is be sufficient to only include
the `imgCIF` dictionary?
2. None of the example data blocks follow Rule 1, that is, none of them contain the `_audit_conform.dict_name` data item at all.
3. Rule 4, point 2. I suggest minor typographical changes. Category names should be capitalised and `_diffrn_detector_element` changed to `DIFFRN_DETECTOR_ELEMENT`.
4. Complex example: given that the experiment only uses a single detector, shouldn't data items like `_diffrn_detector.number_of_axes` appear in the `overall` data block instead of `wav1_temp1` (and presumably all other blocks). Or am I misinterpreting rule 7?
5. Maybe multiple save frames could be used instead of multiple data blocks? For example, one could define a single `overall` data block and reassign the rest of the data blocks as its save frames. This would naturally bundle the data together and make it more easily concatenatable (currently this is a bit of a problem since the `overall` data frame may occur anywhere in the file). However, this may go against the standard practices of CIF2 since save frames are currently only used in CIF dictionaries. 
6. It would be useful to add the link to the automatically-generated DDLm version of the `imgCIF` dictionary that is mentioned at the end of the document. I assume it's the https://github.com/COMCIFS/imgCIF?

Finally, it would be extremely useful to have at least a rudimentary piece of software that actually reads the proposed data files and checks them against the requirements or/and tries to establish the correct inter-data block relations. This would surely demonstrate if the specification strikes the correct balance of flexibility and complexity.

**Comment by jamesrhester** [comment]
> I am a bit late with my reply, hopefully it is still somewhat relevant. Personally, I found the previous approach of importing the core dictionary and redefining relevant categories as looped slightly more robust since it reused the same import mechanisms as other dictionaries and thus allowed to reuse the existing validation software. However, I assume that this approach has been thoroughly discussed before moving away from it, so there is not much point in bringing it up again.

Thanks for replying. Note that the import/rewrite mechanism would still be valid, and any changes to `Set`/`Loop` classification would be flagged by `_audit.schema` as before. The current guidelines are driven by a need to resolve how a dataset described by any dictionary (whether or not it was the result of a multi-dictionary import) can be spread across multiple data blocks. The DDLm specification is relatively silent on the role played by data blocks, but plenty of powder CIF and modulated structure CIFS are spreading out across many data blocks and so we need to come up with some sort of principles to help the readers and writers of such multi-block extravaganzas to coordinate.  `imgCIF` is another dictionary that becomes very easy to integrate into small-molecule work if multi-block data are allowed.

Regarding your particular points: (1)(2)(3) and (6) thank you for the attention to detail, I will fix if/when the rest is agreed to. 

Regarding (4), unfortunately all categories that begin with `diffrn` have a key data name that is a child of `_diffrn.id`. This is hidden in DDL2 as these key data names are all supposed to be listed in the definition of the parent data name (although I'm not sure that mmCIF/PDBx ever actually did this). The DDLm dictionary will make these explicit. Anyway, because of this child data name we are forced to consider the detector a characteristic of the diffraction data set rather than an independent object.

Regarding (5), save frames have been rejected in CIF data files many times now, presumably to simplify programmers' lives. You'll also notice that a "data block" is deliberately defined to **not** necessarily correspond to a CIF data block, but to any collection of data that can be mapped to a CIF data block. This allows a directory full of files in different formats to be covered by these guidelines just as well as a single file full of CIF data blocks or an HDF5 file full of "entries".  I like the freedom of allowing the context to perform the encapsulation.

> Finally, it would be extremely useful to have at least a rudimentary piece of software that actually reads the proposed data files and checks them against the requirements or/and tries to establish the correct inter-data block relations. This would surely demonstrate if the specification strikes the correct balance of flexibility and complexity.

Yes it would. I haven't been willing to write anything until any obvious problems have been dealt with. The production of the imgCIF example file that you alluded to was a first step to making sure the principles could be applied in practice. We might be at the stage of producing some validation software now as @jcbollinger has not commented further. Plenty of CIF files produced by powder diffraction experiments almost match the guidelines so could be used as starting points.

**Comment by jamesrhester** [comment]
There having been no further comments I will assume agreement and proceed.

**Comment by jamesrhester** [comment]
I have now updated the [original document](https://github.com/COMCIFS/comcifs.github.io/blob/master/draft/multi-block-summary.md) according to the discussions. Note I have added @vaitkus and @jcbollinger as authors, if you would prefer not to be listed please let me know.
